language: python
python:
  - 3.7

sudo: false
install:
  - pip install -r requirements.dev.txt

before_script:
  - source .git-rc
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - export PYTHONPATH="$PYTHONPATH:`pwd`/util"
  - echo "$PYTHONPATH"

script:
  - ./run-tests
