name: Repro
on:
  push:
    branches:
      - bad
      - main
      - good
  workflow_dispatch:
jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Putting a directory with basename `rm` on `$PATH` breaks `openssl-sys` build inside `cargo install parquet2json` below 
          dir=$PWD/a/b/c
          mkdir -p $dir/rm
          export PATH="$dir:$PATH"
          cargo install parquet2json
