name: Repro
on:
  push:
    branches:
      - bad
      - main
      - good
  workflow_dispatch:
jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          export REPO=$PWD/rc
          dir=$REPO/git
          mkdir -p $dir/rm
          echo "Adding git helpers repo $dir to PATH"
          export PATH="$dir:$PATH"
          echo "PATH: $PATH"
          cargo install parquet2json        
