name: Repro
on:
  push:
    branches:
      - bad
      - main
      - good
  workflow_dispatch:
jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./run.sh
